### ISSUE TITLE
选择了一张6K的图片上传报错，大图没事

### ISSUE THREAD

**Issue by wushaoge** [jeasonlzy0216/OkHttpUtils#47]
Caused by: java.lang.StringIndexOutOfBoundsException: length=9; regionStart=6; regionLength=-6
                                                                              at java.lang.String.startEndAndLength(String.java:588)
                                                                              at java.lang.String.substring(String.java:1475)
                                                                              at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
                                                                              at com.lzy.okhttputils.model.HttpParams.guessMimeType(HttpParams.java:147)
                                                                              at com.lzy.okhttputils.model.HttpParams.put(HttpParams.java:91)
                                                                              at com.lzy.okhttputils.model.HttpParams.put(HttpParams.java:87)
                                                                              at com.lzy.okhttputils.request.BaseBodyRequest.params(BaseBodyRequest.java:41)

**Comment by wushaoge** [comment]
= =不是图片的问题，我发现上传的文件名称不能包含 “#” 这个特殊字符，不然就会报错，跟图片大小没关系

**Comment by jeasonlzy0216** [comment]
下一版修复。。这个是系统的方法报出的异常导致库挂掉了。。

**Comment by jeasonlzy0216** [comment]
已修复。最新版本 1.8.0
